Repository Enedis-OSS/chutney, pull requests merged in 2024-11, with the labels that each got.

#16 chore(): fix dsl javadoc generation
  kotlin-dsl/pom.xml
Labels: technical

#15 Upgrade to 3.0.1-SNAPSHOT
  CHANGELOG.md
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release

#18 Doc rework : first pass
  README.md
  docs/docs/common/coming_soon.md
  docs/docs/concepts.md
  docs/docs/documentation/actions/amqp.md
  docs/docs/documentation/actions/assertions.md
  docs/docs/documentation/actions/http.md
  docs/docs/documentation/actions/introduction.md
  docs/docs/documentation/actions/kafka.md
  docs/docs/documentation/actions/micrometer.md
  docs/docs/documentation/actions/selenium.md
  docs/docs/documentation/actions/soap.md
  docs/docs/documentation/actions/ssh.md
  docs/docs/documentation/dataset.md
  docs/docs/documentation/extension/action.md
  docs/docs/documentation/extension/function.md
  docs/docs/documentation/extension/strategy.md
  docs/docs/documentation/functions/extension.md
  docs/docs/documentation/functions/introduction.md
  docs/docs/documentation/intellij_plugin.md
  docs/docs/documentation/scenario_sync.md
  docs/docs/documentation/write.md
  docs/docs/getting_started/constant_dataset.png
  docs/docs/getting_started/demo.md
  docs/docs/getting_started/report_constant.png
  docs/docs/getting_started/report_exec_strategy_for.png
  docs/docs/getting_started/requirements.md
  docs/docs/getting_started/run.md
  docs/docs/getting_started/write.md
  docs/docs/img/swapi-ui-campaign-report.png
  docs/docs/index.md
  docs/docs/installation/advanced_topics.md
  docs/docs/installation/on_premise/details.md
  docs/docs/installation/on_premise/introduction.md
  docs/docs/installation/on_premise/minimal_conf.md
  docs/docs/todo.md
  docs/docs/toolbox.md
  docs/mkdocs.yml
Labels: documentation
