Repository Enedis-OSS/chutney, pull requests merged in 2024-12, with the labels that each got.

#30 fix(ui): Does not display button if user does not have the right for scenario exec
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.ts
Labels: bug

#31 Should use default dataset if no dataset in scheduling campaing
  chutney/action-impl/src/test/java/com/chutneytesting/action/amqp/AmqpBasicConsumeActionTest.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
Labels: bug

#19 fix(ui): fix tab opening after campaign execution replay
  chutney/ui/src/app/modules/campaign/components/execution/history/campaign-executions-history.component.ts
  chutney/ui/src/app/modules/scenarios/components/edition/raw/raw-edition.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  chutney/ui/src/app/shared/event-manager.service.ts
Labels: bug

#35 Kafka multiple values header
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
Labels: bug

#32 compress and index in background
  chutney/server/src/main/java/com/chutneytesting/execution/infra/migration/ZipReportMigration.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ReportConverter.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/ScenarioExecutionReportIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/DataMigrationExecutor.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/DataMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/ExecutionReportMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/infra/ExecutionReportRepository.java
Labels: technical

#39 fix(ui): Prevent title page modification when editing a target
  chutney/ui/src/app/modules/target/targets.routes.ts
Labels: bug

#38 fix(ui): Fix jiraId wording in campaign edition interface
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: bug

#40 fix(server): index execution for only activated scenarios
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/ScenarioExecutionReportJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/ExecutionReportMigrator.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java
  example/pom.xml
Labels: bug

#41 chore(): Delete message in exception constructors
  chutney/action-impl/src/main/java/com/chutneytesting/action/jakarta/JakartaConnectionFactory.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/jakarta/UncheckedJakartaException.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/jms/JmsConnectionFactory.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/jms/UncheckedJmsException.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/delegation/CannotDelegateException.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/EvaluationException.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluator.java
  chutney/engine/src/main/java/com/chutneytesting/engine/infrastructure/delegation/HttpClient.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/Environment.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/EnvironmentService.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/AlreadyExistingEnvironmentException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/AlreadyExistingTargetException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/CannotDeleteEnvironmentException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/EnvVariableNotFoundException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/EnvironmentNotFoundException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/InvalidEnvironmentNameException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/NoEnvironmentFoundException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/SingleEnvironmentException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/UnresolvedEnvironmentException.java
  chutney/environment/src/main/java/com/chutneytesting/environment/infra/JsonFilesEnvironmentRepository.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/environment/HttpEnvironmentApiTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/target/TargetControllerTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/variable/VariableControllerTest.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/AlreadyExistingScenarioException.java
  chutney/server/src/test/java/com/chutneytesting/RestExceptionHandlerTest.java
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/util/HttpClient.kt
Labels: technical

#43 fix(github-actions): fix repository url
  .github/workflows/release-docker-template.yml
  .github/workflows/release-github-template.yml
  pom.xml
Labels: technical

#44 Refacto exception constructor
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/execution/ChutneyScenarioExecutionContext.kt
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/execution/ExecutionUtil.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/execution/UnresolvedScenarioEnvironmentExceptionTest.kt
Labels: technical

#42 Clean scenario execution report
  chutney/ui/src/app/core/model/scenario/scenario-execution-report.model.ts
  chutney/ui/src/app/core/model/scenario/step-execution-report.model.spec.ts
  chutney/ui/src/app/core/model/scenario/step-execution-report.model.ts
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
Labels: enhancement

#45 Spel math functions
  chutney/action-impl/src/main/java/com/chutneytesting/action/function/MathFunctions.java
  chutney/action-impl/src/main/resources/META-INF/extension/chutney.functions
  chutney/action-impl/src/test/java/com/chutneytesting/action/amqp/AmqpBasicConsumeActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/function/MathFunctionsTest.java
  docs/docs/documentation/functions/math.md
  docs/mkdocs.yml
Labels: enhancement
