Repository Enedis-OSS/chutney, pull requests merged in 2025-02, with the labels that each got.

#74 Kafka publish / consume - Allow serialization config
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/ChutneyKafkaProducerFactory.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicPublishAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaClientFactoryHelper.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaConsumerFactory.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaConsumerFactoryFactory.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/ChutneyKafkaProducerFactoryTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionIntegrationTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicPublishActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaConsumerFactoryFactoryTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaConsumerFactoryTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/ssh/SftpActionTest.java
  chutney/action-impl/src/test/resources/security/truststore_empty_pass.jks
  chutney/packaging/local-dev/pom.xml
  docs/docs/documentation/actions/kafka.md
Labels: enhancement

#76 feat(server, server-core, ui): Remove global vars
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/engine/ParametersAcceptanceTest.kt
  acceptance-tests/src/test/resources/blackbox/roles.json
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngine.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/processor/TestCasePreProcessor.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/processor/TestCasePreProcessors.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/globalvar/GlobalVarNotFoundException.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/globalvar/GlobalvarRepository.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/security/Authorization.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsyncTest.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/execution/processor/TestCasePreProcessorTest.java
  chutney/server/src/main/java/com/chutneytesting/RestExceptionHandler.java
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/GwtDataSetPreProcessor.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/RawDataSetPreProcessor.java
  chutney/server/src/main/java/com/chutneytesting/globalvar/api/GlobalVarController.java
  chutney/server/src/main/java/com/chutneytesting/globalvar/infra/FileGlobalVarRepository.java
  chutney/server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/DataSetPreProcessorTest.java
  chutney/server/src/test/java/com/chutneytesting/globalvar/infra/FileGlobalVarRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/scenario/api/GwtTestCaseControllerTest.java
  chutney/server/src/test/resources/raw_scenarios/testcase_for_global_vars.v2.1.json
  chutney/ui/src/app/app-routing.module.ts
  chutney/ui/src/app/core/model/user.model.ts
  chutney/ui/src/app/core/services/global-var.service.ts
  chutney/ui/src/app/core/services/login.service.ts
  chutney/ui/src/app/modules/global-variable/components/global-variable-edition/global-variable-edition.component.html
  chutney/ui/src/app/modules/global-variable/components/global-variable-edition/global-variable-edition.component.scss
  chutney/ui/src/app/modules/global-variable/components/global-variable-edition/global-variable-edition.component.ts
  chutney/ui/src/app/modules/global-variable/global-variable.module.ts
  chutney/ui/src/app/modules/global-variable/global-variable.routes.ts
  chutney/ui/src/app/modules/roles/components/roles.component.html
  chutney/ui/src/app/shared/components/layout/left-menu/chutney-left-menu.items.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
  chutney/ui/src/stories/pages/layout.page.stories.ts
  example/.docker/demo/conf/roles/authorization.json
Labels: technical

#77 feat(server): Remove RawTestCase from domain and infra
  chutney/server/src/main/java/com/chutneytesting/execution/infra/execution/DefaultExecutionRequestMapper.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/execution/ScenarioContent.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/execution/UnmarshalledStepDefinition.java
  chutney/server/src/main/java/com/chutneytesting/scenario/api/raw/mapper/GwtTestCaseMapper.java
  chutney/server/src/main/java/com/chutneytesting/scenario/api/raw/mapper/RawTestCaseMapper.java
  chutney/server/src/main/java/com/chutneytesting/scenario/domain/raw/RawTestCase.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/TestCaseData.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/execution/DefaultExecutionRequestMapperTest.java
  chutney/server/src/test/resources/raw_scenarios/scenario.json
Labels: technical

#80 Scenario search filter - Encode uri param
  chutney/ui/src/app/core/services/scenario.service.ts
Labels: bug

#46 feat(server): global search in scenario, campaign and dataset
  chutney/pom.xml
  chutney/server/pom.xml
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/aop/CampaignIndexingAspect.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/index/CampaignIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignEntity.java
  chutney/server/src/main/java/com/chutneytesting/dataset/infra/aop/DatasetIndexingAspect.java
  chutney/server/src/main/java/com/chutneytesting/dataset/infra/index/DatasetIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/aop/ExecutionReportIndexingAspect.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/index/ExecutionReportIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/api/SearchController.java
  chutney/server/src/main/java/com/chutneytesting/index/api/dto/Hit.java
  chutney/server/src/main/java/com/chutneytesting/index/domain/AbstractIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/domain/IndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/domain/IndexService.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/CustemChutneyAnalyzer.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/IndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/LuceneIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/config/IndexConfig.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/config/OnDiskIndexConfig.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/AbstractMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/CampaignMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/DatasetMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/ExecutionReportMigrator.java
  chutney/server/src/main/java/com/chutneytesting/migration/domain/ScenarioMigrator.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/aop/ScenarioIndexingAspect.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/index/ScenarioIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
  chutney/server/src/test/java/com/chutneytesting/index/domain/IndexRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/index/infra/IndexRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/index/infra/LuceneIndexRepositoryTest.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  chutney/server/src/test/java/util/infra/TestInfraConfiguration.java
  chutney/ui/src/app/core/model/search/hit.model.ts
  chutney/ui/src/app/core/model/search/index.ts
  chutney/ui/src/app/core/services/search.service.ts
  chutney/ui/src/app/modules/campaign/campaign.routes.ts
  chutney/ui/src/app/modules/dataset/dataset.routes.ts
  chutney/ui/src/app/modules/scenarios/scenario.routes.ts
  chutney/ui/src/app/shared/components/layout/header/chutney-main-header.component.html
  chutney/ui/src/app/shared/components/layout/header/chutney-main-header.component.scss
  chutney/ui/src/app/shared/components/layout/header/chutney-main-header.component.ts
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.html
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.scss
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.ts
  chutney/ui/src/app/shared/shared.module.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
  chutney/ui/src/assets/style/layout/header/_header-base.scss
Labels: enhancement

#81 Fix encoding for keyword in lucene search
  chutney/server/src/test/java/com/chutneytesting/index/domain/IndexRepositoryTest.java
  chutney/ui/src/app/core/model/search/hit.model.ts
  chutney/ui/src/app/core/services/search.service.ts
Labels: bug

#82 Remove sql fulltext search
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/AggregatedRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/api/AggregatedTestCaseController.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/TestCaseRepositoryAggregator.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java
  chutney/server/src/test/java/com/chutneytesting/scenario/infra/TestCaseRepositoryAggregatorTest.java
  chutney/server/src/test/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepositoryTest.java
  chutney/ui/src/app/core/services/scenario.service.ts
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.html
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.ts
Labels: technical
