Repository Enedis-OSS/chutney, pull requests merged in 2025-03, with the labels that each got.

#73 Feat/stateless auth sso
  chutney/action-impl/src/test/java/com/chutneytesting/action/function/MathFunctionsTest.java
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/local-dev/src/main/resources/application-ldap-auth.yml
  chutney/packaging/local-dev/src/main/resources/application-sso-auth.yml
  chutney/packaging/local-dev/src/main/resources/application.yml
  chutney/packaging/local-dev/src/test/resources/sso/.env
  chutney/packaging/local-dev/src/test/resources/sso/README.md
  chutney/packaging/local-dev/src/test/resources/sso/package.json
  chutney/packaging/local-dev/src/test/resources/sso/sso-oidc.mjs
  chutney/server/pom.xml
  chutney/server/src/main/java/com/chutneytesting/security/ChutneyWebSecurityConfig.java
  chutney/server/src/main/java/com/chutneytesting/security/HttpLoginFailureHandler.java
  chutney/server/src/main/java/com/chutneytesting/security/HttpLoginSuccessHandler.java
  chutney/server/src/main/java/com/chutneytesting/security/api/SsoOpenIdConnectConfigDto.java
  chutney/server/src/main/java/com/chutneytesting/security/api/SsoOpenIdConnectController.java
  chutney/server/src/main/java/com/chutneytesting/security/api/SsoOpenIdConnectMapper.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/SpringUserService.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/UserDetailsServiceHelper.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/handlers/Http401FailureHandler.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/handlers/HttpEmptyLogoutSuccessHandler.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/handlers/HttpLoginSuccessHandler.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/jwt/ChutneyJwtAuthenticationConverter.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/jwt/ChutneyJwtProperties.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/jwt/JwtUtil.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/memory/InMemorySecurityConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/sso/OAuth2TokenAuthenticationFilter.java
  chutney/server/src/main/java/com/chutneytesting/security/infra/sso/SsoOpenIdConnectConfigProperties.java
  chutney/server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  chutney/server/src/test/resources/blackbox/application.yml
  chutney/ui/package-lock.json
  chutney/ui/package.json
  chutney/ui/src/app/app.module.ts
  chutney/ui/src/app/core/components/login/login.component.html
  chutney/ui/src/app/core/components/login/login.component.scss
  chutney/ui/src/app/core/components/login/login.component.ts
  chutney/ui/src/app/core/core.module.ts
  chutney/ui/src/app/core/guards/auth.guard.ts
  chutney/ui/src/app/core/services/auth.app.initializer.factory.ts
  chutney/ui/src/app/core/services/auth.interceptor.ts
  chutney/ui/src/app/core/services/jwt.service.ts
  chutney/ui/src/app/core/services/login.service.ts
  chutney/ui/src/app/core/services/oauth2-content-type-interceptor.service.ts
  chutney/ui/src/app/core/services/scenario-execution.service.ts
  chutney/ui/src/app/core/services/sso.service.ts
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.spec.ts
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.spec.ts
  chutney/ui/src/app/shared/error-interceptor.service.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
  kotlin-dsl/pom.xml
Labels: enhancement

#94 Standardize id field definition among each index repository
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/index/CampaignIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/dataset/infra/index/DatasetIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/index/ExecutionReportIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/LuceneIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/config/OnDiskIndexConfig.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/index/ScenarioIndexRepository.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  chutney/server/src/test/java/util/infra/TestInfraConfiguration.java
Labels: bug

#95 fix(ui): Fix parsing big numbers
  chutney/ui/package-lock.json
  chutney/ui/package.json
  chutney/ui/src/app/core/services/scenario-execution.service.ts
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  chutney/ui/src/app/shared/pipes/prettyPrint.pipe.ts
  chutney/ui/src/app/shared/pipes/stringify.pipe.ts
Labels: bug

#96 fix(kotlin-dsl): remove deprecated
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyActionExtensions.kt
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctions.kt
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyScenarioExtensions.kt
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctionsTest.kt
Labels: technical

#99 fix(ui): Fix error message fo campaign when saving duplicated scenari…
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: bug

#101 Clean login i18n
  chutney/ui/src/app/core/components/login/login.component.html
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: technical

#97 Manage error on rx subscribe
  chutney/engine/src/main/java/com/chutneytesting/engine/api/execution/EmbeddedTestEngine.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/RxBus.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/step/Step.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/report/CannotGenerateReportException.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/report/Reporter.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/report/ReporterTest.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
Labels: bug

#104 fix(ui): Fix prettyPrint with null object
  chutney/ui/src/app/shared/pipes/prettyPrint.pipe.spec.ts
  chutney/ui/src/app/shared/pipes/prettyPrint.pipe.ts
Labels: bug

#103 Example demo : Add jwt configuration + clean
  chutney/packaging/local-api-unsecure/src/main/resources/logback.xml
  chutney/packaging/local-dev/src/main/resources/application.yml
  chutney/packaging/local-dev/src/main/resources/logback.xml
  docs/docs/index.md
  example/.docker/demo/spring-config/application.yml
  example/.docker/dev-docker-compose-demo.yml
  example/.docker/supervision/grafana/datasources/datasources.yml
  example/.docker/supervision/prometheus/prometheus.yml
  example/.gitignore
Labels: bug
