Repository Enedis-OSS/chutney, pull requests merged in 2025-05, with the labels that each got.

#133 Limit update to completely executed scenario
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
Labels: enhancement

#122 fix(ui): Fix frozen search bar while typing and searching
  chutney/ui/src/app/core/model/search/hit.model.ts
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.html
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.ts
Labels: bug

#119 Fix list execution performance
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/dataset/DataSet.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntityTest.java
  chutney/ui/src/app/core/model/dataset.model.ts
  chutney/ui/src/app/core/services/scenario-execution.service.ts
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.ts
  chutney/ui/src/app/modules/campaign/components/execution/history/list/campaign-executions.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.ts
  chutney/ui/src/app/shared/tools/dataset-utils.ts
Labels: bug

#135 Clean Bootstrap Tooltip usage
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html
  chutney/ui/src/app/modules/campaign/components/execution/history/list/campaign-executions.component.html
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.html
  chutney/ui/src/app/modules/environment-variable/list/environments-variables.component.html
  chutney/ui/src/app/modules/environment/list/environments.component.html
  chutney/ui/src/app/modules/execution-search/components/resultExecutionSearchList/execution-search-list.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.html
  chutney/ui/src/app/modules/target/details/target.component.html
  chutney/ui/src/app/modules/target/list/targets.component.html
  chutney/ui/src/app/molecules/dialog/delete-confirm-dialog/confirm-dialog.component.html
  chutney/ui/src/app/shared/components/layout/header/chutney-main-header.component.html
  chutney/ui/src/app/shared/components/layout/left-menu/chutney-left-menu.component.html
  chutney/ui/src/app/shared/components/layout/right-menu/chutney-right-menu.component.html
Labels: technical

#138 Release/3.1.0
  .github/workflows/release-to-central.yml
  CHANGELOG.md
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release

#139 Prepare next development 3.1.1-SNAPSHOT
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: technical

#143 Fixes scenario execution/replay
  chutney/server/src/main/java/fr/enedis/chutney/dataset/api/DataSetMapper.java
  chutney/server/src/main/java/fr/enedis/chutney/dataset/api/ExecutionDatasetDto.java
  chutney/server/src/main/java/fr/enedis/chutney/execution/api/CampaignExecutionUiController.java
  chutney/server/src/main/java/fr/enedis/chutney/execution/api/ScenarioExecutionUiController.java
  chutney/server/src/test/java/fr/enedis/chutney/dataset/api/DataSetMapperTest.java
  chutney/server/src/test/java/fr/enedis/chutney/dataset/api/ExecutionDatasetDtoTest.java
  chutney/ui/src/app/core/components/login/login.component.scss
  chutney/ui/src/app/modules/campaign/components/execution/sub/right-side-bar/campaign-execution-menu.component.html
  chutney/ui/src/app/modules/campaign/components/execution/sub/right-side-bar/campaign-execution-menu.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/sub/right-side-bar/scenario-execution-menu.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/sub/right-side-bar/scenario-execution-menu.component.ts
  chutney/ui/src/assets/img/logo.png
  chutney/ui/src/favicon.ico
  docs/docs/img/favicon.ico
  docs/docs/img/logo.png
Labels: bug

#144 Release 3.1.1
  CHANGELOG.md
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release

#145 Prepare next development 3.1.2-SNAPSHOT
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release

#149 feat(action-impl): parametrize minimumMemoryPercentageRequired for sql action
  chutney/action-impl/src/main/java/fr/enedis/chutney/action/sql/SqlAction.java
  chutney/action-impl/src/main/java/fr/enedis/chutney/action/sql/core/DefaultSqlClientFactory.java
  chutney/action-impl/src/main/java/fr/enedis/chutney/action/sql/core/SqlClient.java
  chutney/action-impl/src/main/java/fr/enedis/chutney/action/sql/core/SqlClientFactory.java
  chutney/action-impl/src/test/java/fr/enedis/chutney/action/sql/SqlActionTest.java
  chutney/action-impl/src/test/java/fr/enedis/chutney/action/sql/core/SqlClientTest.java
  chutney/packaging/local-dev/src/main/resources/application.yml
  chutney/tools/src/main/java/fr/enedis/chutney/tools/ChutneyMemoryInfo.java
  docs/docs/documentation/actions/sql.md
  example/.docker/demo/spring-config/application.yml
  kotlin-dsl/src/main/kotlin/fr/enedis/chutney/kotlin/dsl/ChutneyActionExtensions.kt
Labels: enhancement

#150 Fix package declaration in DSL
  .idea/runConfigurations/install_local_api_unsecure_jar.xml
  kotlin-dsl/src/main/kotlin/fr/enedis/chutney/kotlin/synchronize/EnvironmentSynchronizeService.kt
  kotlin-dsl/src/test/kotlin/fr/enedis/chutney/kotlin/synchronize/EnvironmentServiceSynchronizationTest.kt
Labels: technical
