Repository Enedis-OSS/chutney, pull requests merged in 2025-04, with the labels that each got.

#105 Scenario execution - SSE Autorization header
  chutney/packaging/local-api-unsecure/src/main/java/com/chutneytesting/SecurityConfiguration.java
  chutney/ui/src/app/core/services/scenario-execution.service.ts
Labels: bug

#116 feat(action): Add URL encode/decode and duration between functions
  chutney/action-impl/src/main/java/com/chutneytesting/action/function/DateTimeFunctions.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/function/EscapeFunctions.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/function/DateTimeFunctionsTest.java
  docs/docs/documentation/actions/micrometer.md
  docs/docs/documentation/actions/ssh.md
  docs/docs/documentation/functions/classpath.md
  docs/docs/documentation/functions/datetime.md
  docs/docs/documentation/functions/escape.md
  docs/docs/documentation/functions/generate.md
  docs/docs/documentation/functions/nullable.md
Labels: enhancement

#118 XML asserts : guard against null value for placeholder asserts and soft assert for multiple expectations
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/JsonAssertAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/XmlAssertAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/AfterDateAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/BeforeDateAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/ContainsAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/EqualDateAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/GreaterThanAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/GuardedPlaceholderAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/IsEmptyAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/LenientEqualAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/LessThanAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/MatchesStringAsserter.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/PlaceholderAsserterUtils.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/common/JsonUtils.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/assertion/JsonAssertActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/assertion/XmlAssertActionTest.java
Labels: enhancement

#117 Fix/bug demo
  chutney/environment/src/main/java/com/chutneytesting/environment/api/variable/EmbeddedVariableApi.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/EnvironmentService.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/variable/VariableControllerTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/domain/EnvironmentServiceTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/domain/EnvironmentTest.java
  chutney/ui/src/app/modules/execution-search/components/execution-search.component.html
  chutney/ui/src/app/modules/execution-search/components/execution-search.component.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: bug

#121 Add global CORS policy
  chutney/engine/src/main/java/com/chutneytesting/action/api/ActionController.java
  chutney/engine/src/main/java/com/chutneytesting/engine/api/execution/HttpTestEngine.java
  chutney/environment/src/main/java/com/chutneytesting/environment/api/environment/HttpEnvironmentApi.java
  chutney/environment/src/main/java/com/chutneytesting/environment/api/target/TargetController.java
  chutney/environment/src/main/java/com/chutneytesting/environment/api/variable/EnvironmentVariableController.java
  chutney/jira/src/main/java/com/chutneytesting/jira/api/JiraModuleController.java
  chutney/packaging/local-dev/src/main/resources/application.yml
  chutney/server/src/main/java/com/chutneytesting/admin/api/BackupController.java
  chutney/server/src/main/java/com/chutneytesting/admin/api/DatabaseManagementController.java
  chutney/server/src/main/java/com/chutneytesting/admin/api/InfoController.java
  chutney/server/src/main/java/com/chutneytesting/agent/api/NodeNetworkController.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/CampaignController.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/ScheduleCampaignController.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetController.java
  chutney/server/src/main/java/com/chutneytesting/design/api/editionlock/TestCaseEditionController.java
  chutney/server/src/main/java/com/chutneytesting/design/api/plugins/linkifier/LinkifierController.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/CampaignExecutionUiController.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionHistoryController.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionUiController.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/report/search/ExecutionSearchController.java
  chutney/server/src/main/java/com/chutneytesting/feature/api/FeatureController.java
  chutney/server/src/main/java/com/chutneytesting/index/api/SearchController.java
  chutney/server/src/main/java/com/chutneytesting/scenario/api/AggregatedTestCaseController.java
  chutney/server/src/main/java/com/chutneytesting/scenario/api/GwtTestCaseController.java
  chutney/server/src/main/java/com/chutneytesting/security/ChutneyWebSecurityConfig.java
  chutney/server/src/main/java/com/chutneytesting/security/api/AuthorizationController.java
  chutney/server/src/main/java/com/chutneytesting/security/api/SsoOpenIdConnectController.java
  chutney/server/src/main/java/com/chutneytesting/security/api/UserController.java
Labels: enhancement

#120 Check/Clean rxjs subscriptions
  chutney/ui/src/app/core/components/login/login.component.ts
  chutney/ui/src/app/core/services/sso.service.ts
  chutney/ui/src/app/modules/agent-network/components/agent-network-configuration/agent-network-configuration.component.ts
  chutney/ui/src/app/modules/agent-network/components/agent-network/agent-network.component.ts
  chutney/ui/src/app/modules/agent-network/components/network-graph/network-graph.component.ts
  chutney/ui/src/app/modules/backups/components/backups-admin.component.ts
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.ts
  chutney/ui/src/app/modules/campaign/components/campaign-scheduling/campaign-scheduling.component.ts
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.ts
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.ts
  chutney/ui/src/app/modules/campaign/components/execution/history/campaign-executions-history.component.ts
  chutney/ui/src/app/modules/campaign/components/execution/sub/right-side-bar/campaign-execution-menu.component.ts
  chutney/ui/src/app/modules/dataset/components/dataset-edition/dataset-edition.component.ts
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.ts
  chutney/ui/src/app/modules/environment-variable/list/environments-variables.component.ts
  chutney/ui/src/app/modules/environment/list/environments.component.ts
  chutney/ui/src/app/modules/execution-search/components/execution-search.component.ts
  chutney/ui/src/app/modules/metrics/components/metrics.component.ts
  chutney/ui/src/app/modules/plugins/components/jira/jira.component.ts
  chutney/ui/src/app/modules/plugins/components/linkifier/linkifier.component.ts
  chutney/ui/src/app/modules/roles/components/roles.component.ts
  chutney/ui/src/app/modules/scenarios/components/edition/edition-info/edition-info.component.ts
  chutney/ui/src/app/modules/scenarios/components/edition/raw/raw-edition.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/sub/right-side-bar/scenario-execution-menu.component.ts
  chutney/ui/src/app/modules/scenarios/components/scenario-jira-links-modal/scenario-jira-links-modal.component.ts
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.ts
  chutney/ui/src/app/modules/scenarios/components/sub/scenario-campaigns/scenario-campaigns.component.ts
  chutney/ui/src/app/modules/target/details/target.component.ts
  chutney/ui/src/app/modules/target/list/targets.component.ts
  chutney/ui/src/app/modules/vacuum/components/vacuum.component.ts
  chutney/ui/src/app/shared/alert.service.ts
  chutney/ui/src/app/shared/components/dataset-selection/dataset-selection.component.ts
  chutney/ui/src/app/shared/components/dataset/forms-data-grid/forms-data-grid.component.ts
  chutney/ui/src/app/shared/components/dataset/forms-key-value/forms-key-value.component.ts
  chutney/ui/src/app/shared/components/execute-modal/scenario-execute-modal.component.ts
  chutney/ui/src/app/shared/components/search-bar/search-bar.component.ts
  chutney/ui/src/app/shared/error-interceptor.service.ts
Labels: technical
